Educap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('miCuenta/', include('myAccount.urls')),
    path('Catalogo/', include('LearningCatalog.urls')),
    path('API/', include('APILessons.urls')),
    path('API/', include('APIAccounts.urls')),
    path('API/', include('APICategory.urls')),
    path('SobreNosotros', include('aboutUs.urls')),
    path('', include('Index.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Index/urls.py
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "Index"

urlpatterns = [
    path('', views.Index, name='Index'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LearningCatalog/urls.py
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "LearningCatalog"

urlpatterns = [
    path('Categorias', views.primaryCategory, name='primaryCategory'),
    path('Categorias/<int:pk>', views.subCategories, name='subCategories'),
    path('Busqueda/Categorias', views.searchCategory, name="searchCategory"),
    path('Lecciones', views.listLesson, name="listLesson"),
    path('Lecciones/<int:pk>', views.readLesson, name="readLesson"),
    path('Busqueda/Lecciones', views.searchLesson, name="searchLesson"),
    path('Categoria/Lecciones/<int:pk>', views.filterLessonsByCategory,
         name="filterLessonsByCategory"),
    path('Lecciones/FollowLesson',
         views.followLesson, name="followLesson"),
    path('CheckFollow/', views.checkFollow, name="checkFollow")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aboutUs/urls.py
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "aboutUs"

urlpatterns = [
    path('', views.AboutUs, name='AboutUs'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myAccount/urls.py
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from . import views

app_name = "myAccount"

urlpatterns = [
    path('', views.myAccount, name="myAccount"),
    path('Registro/', views.studentCreate, name="studentCreate"),
    path('Modificar/', views.studentUpdate, name="studentUpdate"),
    path('Información/', views.studentRead, name="studentRead"),
    path('Baja', views.studentDelete, name="studentDelete"),
    path('LeccionesQueSigo/', views.followedLessons, name="followedLessons"),
    path('Redirect/', views.loginRedirect, name="loginRedirect")
]

LearningCatalog/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from accounts.models import UserModel, Estudiante
# Creacion de modelos.

# Tipos de archivos para determinar cual icono utilizaremos en la interfaz
FILETYPES = [
    ('PDF', 'Archivo PDF'),
    ('IMG', 'Imagen'),
    ('DOC', 'Archivo Word'),
    ('PPX', 'PowerPoint'),
    ('XLX', 'Archivo Excel'),
    ('ANY', 'Archivo')
]

# Clase de modelos para crear las tablas en la base de datos


class Categoria(models.Model):
    # Todos los atributos vienen de la importacion de models y son clases predefinidas de django para la creacion de tablas
    nombre = models.CharField("Nombre", max_length=30)
    descripcion = models.TextField("Descripción", max_length=100)
    imagen = models.ImageField("Imagen", upload_to='uploads/categories/img')
    fechaCreada = models.DateTimeField("Fecha de creación", auto_now_add=True)
    # Atributo que se refiere a la misma clase para poder tener nesting de categorias
    categoriaPadre = models.ForeignKey(
        'self', blank=True, null=True, on_delete=CASCADE, verbose_name="Categoria perteneciente")

    def __str__(self):
        return f"{self.nombre}"


class Leccion(models.Model):

    titulo = models.CharField(max_length=150)
    descripcion = models.TextField("Descripción", max_length=500)
    imagen = models.ImageField(upload_to='uploads/lessons/img')
    fecha = models.DateField(
        "Fecha de creación", auto_now=False, auto_now_add=True)
    aprobacion = models.BooleanField("Aprobación", default=False)
    category = models.ForeignKey(
        Categoria, on_delete=CASCADE, verbose_name="Categoria")
    # Verbose name y verbose name plural para cambiar el nombre de la seccion en el panel administrativo
    created_by = models.ForeignKey(UserModel, on_delete=CASCADE)

    class Meta:
        verbose_name = ("Lección")
        verbose_name_plural = ("Lecciones")
        
    def __str__(self):
        return f"{self.titulo}"


class Archivo(models.Model):
    orden = models.PositiveSmallIntegerField("Orden de aparición")
    titulo = models.CharField(max_length=150)
    descripcion = models.TextField("Descripción", max_length=500)
    path = models.FileField("Archivo", upload_to='uploads/files')
    lipo = models.CharField("Tipo de archivo", choices=FILETYPES, max_length=3)
    leccion = models.ForeignKey(Leccion, on_delete=CASCADE)


class Video(models.Model):
    titulo = models.CharField(max_length=150)
    descripcion = models.TextField("Descripción", max_length=500)
    link = models.CharField(max_length=500)
    leccion = models.ForeignKey(Leccion, on_delete=CASCADE)


class Estudiante_Leccione(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete=CASCADE)
    leccion = models.ForeignKey(Leccion, on_delete=CASCADE)

LearningCatalog/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from . import urls
from LearningCatalog.models import Categoria
import logging
from .models import *
from accounts.models import *
import json
from copy import copy
from django.db.models import Q
# Create your views here.


def primaryCategory(request):
    # Respuesta HTTPS donde django procesa el html y presenta la ingerfaz
    return render(request, "LearningCatalog/primaryCategory.html", {
        # Contexto para procesar la interfaz donde se realiza un query a la base de datos y obtenemos todas las categorias
        "categories": Categoria.objects.all().order_by('nombre'),

    })


def subCategories(request, pk):
    category = Categoria.objects.get(pk=pk)
    subCategory = Categoria.objects.filter(categoriaPadre=category)
    logging.error(subCategory)
    return render(request, "LearningCatalog/subcategory.html", {
        "category": Categoria.objects.get(pk=pk),
        "subCategories": subCategory,
    })


def searchCategory(request):
    if request.method == "POST":
        search = request.POST.get('searchBar')
        return render(request, "LearningCatalog/searchBar.html", {
            "categories": Categoria.objects.filter(Q(nombre__icontains=search) | Q(descripcion__icontains=search)),
            "search": search
        })


def listLesson(request):
    lessons = Leccion.objects.all().order_by('titulo')
    return render(request, "LearningCatalog/lessonList.html", {
        "lessons": lessons
    })


def readLesson(request, pk):
    lesson = Leccion.objects.get(pk=pk)
    files = Archivo.objects.filter(leccion=pk).order_by('orden')
    videos = Video.objects.filter(leccion=pk)

    # Convertir urls de youtube a urls de Embed

    arrVidL = [video.link for video in videos]
    arrVidT = [video.titulo for video in videos]
    arrVidD = [video.descripcion for video in videos]

    videoCode = []
    vidLists = []
    for i in arrVidL:
        arrLinks = []
        arrLinks = i.split('/')

        videoCode.append(arrLinks[3])

    vidLists = list(zip(arrVidT, arrVidD, videoCode))

    ##############################################

    leccion = Leccion.objects.get(pk=pk)

    if request.user.is_anonymous:
        follow = True
    else:
        if request.user.is_staff:

            follow = False
        else:
            estudiante = Estudiante.objects.get(user=request.user)
            if Estudiante_Leccione.objects.filter(estudiante=estudiante, leccion=leccion).exists():
                follow = True
            else:
                follow = False
    return render(request, "LearningCatalog/lesson.html", {
        "lesson": lesson,
        "files": files,
        "follow": follow,
        "vidLists": vidLists,


    })


def searchLesson(request):
    if request.method == "POST":
        search = request.POST.get('searchBar')
        return render(request, "LearningCatalog/lessonList.html", {
            "lessons": Leccion.objects.filter(Q(titulo__icontains=search) | Q(descripcion__icontains=search)),
            "search": search
        })


def filterLessonsByCategory(request, pk):
    subCategory = Categoria.objects.get(pk=pk)
    lessons = Leccion.objects.filter(category=subCategory)
    return render(request, "LearningCatalog/lessonList.html", {
        "lessons": lessons
    })


def followLesson(request):
    if request.is_ajax():
        if request.method == "POST":
            jsonObject = json.load(request)['jsonBody']
            pk = jsonObject["pk"]
            estudiante = Estudiante.objects.get(user=request.user)
            leccion = Leccion.objects.get(pk=pk)
            if Estudiante_Leccione.objects.filter(estudiante=estudiante, leccion=leccion).exists():
                newUnfollow = Estudiante_Leccione.objects.get(
                    estudiante=estudiante,
                    leccion=leccion
                )
                newUnfollow.delete()
                return HttpResponse("follow")
            else:
                newFollow = Estudiante_Leccione(
                    estudiante=estudiante,
                    leccion=leccion
                )
                newFollow.save()
                return HttpResponse("unFollow")


def checkFollow(request):
    return HttpResponse()

LearningCatalog/templates/LearningCatalog/layout.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'accounts/img/favicon.ico' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'LearningCatalog/css/master.css' %}">
    <script src="https://kit.fontawesome.com/cff12e1c4b.js" crossorigin="anonymous"></script>
    <script src="{% static 'LearningCatalog/js/main.js' %}"></script>

</head>

<body>
    {% include './navBar.html' %}
    {% block body %}
    {% endblock %}
    <footer class="bg-white mt-5 mb-0 mt-auto">
        <div class="container py-5">
            <div class="row py-4">
                <div class="col-lg-4 col-md-6 mb-4 mb-lg-0"><img src="" alt="" width="180" class="mb-3">
                    <img src="{% static 'accounts/img/logoEducap.png' %}" alt="" width="180" class="mb-3">
                    <p class="font-italic text-muted">Lema de la empresa</p>
                    <ul class="list-inline mt-4">
                        <li class="list-inline-item"><a href="#" target="_blank" title="twitter"><i
                                    class="fa fa-twitter"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#" target="_blank" title="facebook">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#" target="_blank" title="instagram">
                                <i class="fa fa-instagram"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#" target="_blank" title="pinterest">
                                <i class="fa fa-pinterest"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#" target="_blank" title="vimeo">
                                <i class="fa fa-vimeo"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                    <h6 class="text-uppercase font-weight-bold mb-4">Contenido</h6>
                    <ul class="list-unstyled mb-0">
                        <li class="mb-2"><a href="{% url 'LearningCatalog:listLesson' %}"
                                class=" text-muted">Lecciones</a></li>
                        <li class="mb-2"><a href="{% url 'LearningCatalog:primaryCategory' %}"
                                class="text-muted">Categorias</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                    <h6 class="text-uppercase font-weight-bold mb-4">Educap</h6>
                    <ul class="list-unstyled mb-0">
                        <li class="mb-2"><a href="{% url 'myAccount:myAccount' %}" class="text-muted">Mi cuenta</a></li>
                        <li class="mb-2"><a href="{% url 'myAccount:studentRead' %}" class="text-muted">Mi información
                                personal</a>
                        </li>
                        <li class="mb-2"><a href="{% url 'myAccount:followedLessons' %}" class="text-muted">Mis
                                lecciones seguidas</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6 mb-lg-0">
                    <h6 class="text-uppercase font-weight-bold mb-4">Información de contacto</h6>
                    <p class="text-muted mb-4">Información de contacto, direccion del lugar.
                    </p>
                    <p class="text-muted mb-4">Información de contacto por telefono.</p>
                </div>
            </div>
        </div>

        <!-- Copyrights -->
        <div class="bg-light py-4">
            <div class="container text-center">
                <p>Designed and developed with &#128150; by CodeX <a href="https://www.instagram.com/chalajr/">Instagram
                        -
                        Chalajr</a></p>
                <p>Copyright &copy; <script>
                        document.write(new Date().getFullYear());
                    </script>, Educap</p>
            </div>
        </div>
    </footer>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
    </script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
</body>

</html>

LearningCatalog/templates/LearningCatalog/lessonList.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<head>
    <title>Lecciones</title>
</head>

<div class="container">
    <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-5">
        <div class="row">
            <div class="col-12">
                <h1 class="display-4 mb-3">
                    Lecciones
                    <span class="material-icons-outlined align-middle blueIcons" style="font-size: 48px;">
                        menu_book
                    </span>
                </h1>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-12">
                <form action="{% url 'LearningCatalog:searchLesson' %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">
                                Buscar
                                <span class="material-icons-outlined float-right ml-2">
                                    search
                                </span>
                            </span>
                        </div>
                        <input type="text" class="form-control" aria-label="Sizing example input"
                            aria-describedby="inputGroup-sizing-default" id="searchBar" name="searchBar"
                            value="{{search}}" placeholder="Titulo o descripción">
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            {% for lesson in lessons %}
            {% if lesson.aprobacion %}
            <div class="col-12 col-md-6 col-lg-4 mt-3">
                <div class="card mx-auto mx-md-0" style="width: 18rem;">
                    <img src="{{lesson.imagen.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{lesson.titulo}}</h5>
                        <p class="card-text">{{lesson.descripcion}}</p>
                        <a href="{% url 'LearningCatalog:readLesson' lesson.pk %}" class="btn btn-primary">
                            Ver contenido
                            <span class="material-icons-outlined align-middle">
                                arrow_forward
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            {% endif %}
            {% empty %}
            <div class="col">
                <p>No hay lecciones</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

LearningCatalog/templates/LearningCatalog/navBar.html
{% load static %}
{% load static %}
<nav class="navbar navbar-expand-md navbar-light bg-light shadow">
    <a class="navbar-brand" href="{% url 'Index:Index' %}">
        <img src="{% static 'accounts/img/logoEducapManzana.png' %}" alt="" width="50" height="45">
        EduCap
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link font-weight-bold" href="{% url 'LearningCatalog:listLesson' %}">
                    Lecciones
                    <span class="material-icons-outlined align-middle blueIcons float-left mr-1">
                        menu_book
                    </span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link font-weight-bold" href="{% url 'LearningCatalog:primaryCategory' %}">
                    Categorías
                    <span class="material-icons-outlined align-middle blueIcons float-left mr-1">
                        space_dashboard
                    </span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link font-weight-bold" href="{% url 'aboutUs:AboutUs' %}">
                    Acerca de nosotros
                    <span class="material-icons-outlined align-middle blueIcons float-left mr-1">
                        business
                    </span>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
            <!--Dropdown user dashboard-->
            <li class="nav-item dropdown">
                {% if user.is_authenticated %}
                <a class="nav-link font-weight-bold dropdown-toggle" href="#" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="material-icons-outlined align-middle blueIcons">
                        account_circle
                    </span>
                    {{ user.first_name }}
                    {{ user.last_name }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="width: 200px; left: -55px;">
                    <a class="dropdown-item" href="{% url 'myAccount:myAccount' %}">
                        <span class="material-icons-outlined align-middle blueIcons float-left  mr-1">
                            manage_accounts
                        </span>
                        Cuenta
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">
                        <span class="material-icons-outlined align-middle blueIcons float-left mr-1">
                            logout
                        </span>
                        Cerrar sesión
                    </a>
                </div>
                {% else %}
                <a class="nav-link font-weight-bold dropdown-toggle" href="#" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="material-icons-outlined align-middle blueIcons">
                        account_circle
                    </span>
                    Inicia sesión
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="width: 200px; left: -55px;">
                    <a class="dropdown-item" href="{% url 'login' %}">
                        <span class="material-icons-outlined align-middle blueIcons float-left mr-1">
                            login
                        </span>
                        Iniciar sesión
                    </a>
                    <a class="dropdown-item" href="{% url 'myAccount:studentCreate' %}">
                        <span class="material-icons-outlined align-middle blueIcons float-left mr-1">
                            app_registration
                        </span>
                        Registrate
                    </a>

                </div>
                {% endif %}
            </li>
            <!--Dropdown user dashboard-->
        </ul>
    </div>
</nav>

LearningCatalog/templates/LearningCatalog/primaryCategory.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<head>
    <title>Categorías</title>
</head>

<div class="container">
    <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-5">
        <div class="row">
            <div class="col-12">
                <h1 class="display-4 mb-3">
                    Categorías
                    <span class="material-icons-outlined align-middle blueIcons" style="font-size: 48px;">
                        space_dashboard
                    </span>
                </h1>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-12">
                <form action="{% url 'LearningCatalog:searchCategory' %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">
                                Buscar
                                <span class="material-icons-outlined float-right ml-2">
                                    search
                                </span>
                            </span>
                        </div>
                        <input type="text" class="form-control" aria-label="Sizing example input"
                            aria-describedby="inputGroup-sizing-default" id="searchBar" name="searchBar"
                            placeholder="Nombre o descripción">
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            {% for category in categories %}
            {% if not category.categoriaPadre %}
            <div class="col-12 col-md-6 col-lg-4 mt-3">
                <div class="card mx-auto mx-md-0" style="width: 18rem;">
                    <img src="{{category.imagen.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{category.nombre}}</h5>
                        <p class="card-text">{{category.descripcion}}</p>
                        <a href="{% url 'LearningCatalog:subCategories' category.pk %}" class="btn btn-primary">
                            Ver subcategorias
                            <span class="material-icons-outlined align-middle">
                                arrow_forward
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            {% else %}
            {% endif %}
            {% empty %}
            <div class="col">
                <p>No hay categorias</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

LearningCatalog/templates/LearningCatalog/searchBar.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<head>
    <title>Categorías</title>
</head>

<div class="container">
    <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-5">
        <div class="row">
            <div class="col-12">
                <h1 class="display-4 mb-3">
                    Categorías
                    <span class="material-icons-outlined align-middle blueIcons" style="font-size: 48px;">
                        space_dashboard
                    </span>
                </h1>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-12">
                <form action="{% url 'LearningCatalog:searchCategory' %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">
                                Buscar
                                <span class="material-icons-outlined float-right ml-2">
                                    search
                                </span>
                            </span>
                        </div>
                        <input type="text" class="form-control" aria-label="Sizing example input"
                            aria-describedby="inputGroup-sizing-default" id="searchBar" name="searchBar"
                            value="{{search}}" placeholder="Nombre o descripción">
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            {% for category in categories %}
            <div class="col-lg-4 mt-3">
                <div class="card" style="width: 18rem;">
                    <img src="{{category.imagen.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{category.nombre}}</h5>
                        <p class="card-text">{{category.descripcion}}</p>

                        {% if category.categoriaPadre == None %}
                        <a href="{% url 'LearningCatalog:subCategories' category.pk %}" class="btn btn-primary">
                            Ver subcategorias
                            <span class="material-icons-outlined align-middle">
                                arrow_forward
                            </span>
                        </a>
                        {% else %}
                        <a href="{% url 'LearningCatalog:filterLessonsByCategory' category.pk %}"
                            class="btn btn-primary">
                            Ver contenido
                            <span class="material-icons-outlined align-middle">
                                arrow_forward
                            </span>
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div> {% empty %} <div class="col">
                <p>No hay categorias</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

LearningCatalog/templates/LearningCatalog/subcategory.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<head>
    <title>Categorías</title>
</head>

<div class="container">
    <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-5">
        <div class="row">
            <div class="col-12">
                <h1 class="display-4 mb-3">
                    {{category.nombre}}
                    <span class="material-icons-outlined align-middle blueIcons" style="font-size: 48px;">
                        space_dashboard
                    </span>
                </h1>
            </div>
        </div>
        <hr>
        <div class="row">
            {% for subCategory in subCategories %}
            <div class="col-12 col-md-6 col-lg-4 mt-3">
                <div class="card mx-auto mx-md-0" style="width: 18rem;">
                    <img src="{{subCategory.imagen.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{subCategory.nombre}}</h5>
                        <p class="card-text">{{subCategory.descripcion}}</p>
                        <a href="{% url 'LearningCatalog:filterLessonsByCategory' subCategory.pk %}"
                            class="btn btn-primary">
                            Ver contenido
                            <span class="material-icons-outlined align-middle">
                                arrow_forward
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col">
                <p>No hay categorias</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}