Educap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('miCuenta/', include('myAccount.urls')),
    path('Catalogo/', include('LearningCatalog.urls')),
    path('API/', include('APILessons.urls')),
    path('API/', include('APIAccounts.urls')),
    path('API/', include('APICategory.urls')),
    path('SobreNosotros', include('aboutUs.urls')),
    path('', include('Index.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Index/urls.py
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "Index"

urlpatterns = [
    path('', views.Index, name='Index'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LearningCatalog/urls.py
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "LearningCatalog"

urlpatterns = [
    path('Categorias', views.primaryCategory, name='primaryCategory'),
    path('Categorias/<int:pk>', views.subCategories, name='subCategories'),
    path('Busqueda/Categorias', views.searchCategory, name="searchCategory"),
    path('Lecciones', views.listLesson, name="listLesson"),
    path('Lecciones/<int:pk>', views.readLesson, name="readLesson"),
    path('Busqueda/Lecciones', views.searchLesson, name="searchLesson"),
    path('Categoria/Lecciones/<int:pk>', views.filterLessonsByCategory,
         name="filterLessonsByCategory"),
    path('Lecciones/FollowLesson',
         views.followLesson, name="followLesson"),
    path('CheckFollow/', views.checkFollow, name="checkFollow")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myAccount/urls.py
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from . import views

app_name = "myAccount"

urlpatterns = [
    path('', views.myAccount, name="myAccount"),
    path('Registro/', views.studentCreate, name="studentCreate"),
    path('Modificar/', views.studentUpdate, name="studentUpdate"),
    path('Información/', views.studentRead, name="studentRead"),
    path('Baja', views.studentDelete, name="studentDelete"),
    path('LeccionesQueSigo/', views.followedLessons, name="followedLessons"),
    path('Redirect/', views.loginRedirect, name="loginRedirect")
]

myAccount/models.py
from django.db import models

# Create your models here.

myAccount/forms.py
from django.db.models import fields
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm
from accounts.models import *


class UserForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('email', 'first_name', 'last_name')


class userFormChange(UserChangeForm):
    class Meta:
        model = UserModel
        exclude = '__all__'
        fields = ('first_name', 'last_name',)


class StudentForm(ModelForm):
    class Meta:
        model = Estudiante
        fields = ('edad',)

myAccount/views.py
from django.db.models.deletion import ProtectedError
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from LearningCatalog.models import Estudiante_Leccione
from accounts.models import *
from .forms import *
import logging
from django.contrib.auth.decorators import login_required
# Create your views here.


def studentCreate(request):
    if request.user.is_authenticated:
        return redirect('myAccount:myAccount')
    else:
        # Metodo post para el registro
        if request.method == "POST":

            # Guardamos formularios con el contenido enviado por el usuario en las variables
            studentFormRequest = StudentForm(request.POST, prefix='student')
            userFormRequest = UserForm(request.POST, prefix='user')

            # Revisamos que los formularios del usuario sea correcto
            if studentFormRequest.is_valid() and userFormRequest.is_valid():

                logging.error("Es valido")

                # Guardado y creacion del nuevo usuario
                # Se guarda el registro de usuario
                userFormRequest.save()
                userFormSave = userFormRequest.save()

                # Se crea el registro del estudiante pero no se guarda
                studentFormSave = studentFormRequest.save(commit=False)
                # Asignamos el usuario al estudiante
                studentFormSave.user = userFormSave
                # Guardamos el estudiante
                studentFormSave.save()
                return render(request, "myAccount/successfulStudentCreate.html")
            else:
                logging.error("Es invalido")
                return render(request, "myAccount/studentCreate.html", {
                    "studentForm": studentFormRequest,
                    "userForm": userFormRequest
                })
        return render(request, "myAccount/studentCreate.html", {
            "studentForm": StudentForm(prefix='student'),
            "userForm": UserForm(prefix='user')
        })


@login_required(login_url="login")
def studentRead(request):
    if request.user.is_staff:
        return redirect('admin:index')
    # Obtenemos el objeto de usuario con request.user
    user = UserModel.objects.get(pk=request.user.pk)
    # Obtenemos el objeto de estudiante refiriendonos al usuario
    student = Estudiante.objects.get(user=user)

    return render(request, "myAccount/studentRead.html", {
        "user": user,
        "student": student
    })


@login_required(login_url="login")
def studentUpdate(request):
    # Obtenemos el objeto de usuario con request.user
    user = UserModel.objects.get(pk=request.user.pk)
    # Obtenemos el objeto de estudiante refiriendonos al usuario
    student = Estudiante.objects.get(user=user)
    # Metodo post para el registro
    if request.method == "POST":

        # Guardamos formularios con el contenido enviado por el usuario en las variables
        studentFormRequest = StudentForm(
            request.POST, prefix='student', instance=student)
        userFormRequest = userFormChange(
            request.POST, prefix='user', instance=user)

        # Revisamos que los formularios del usuario sea correcto
        if studentFormRequest.is_valid() and userFormRequest.is_valid():

            logging.error("Es valido")

            # Guardado y creacion del nuevo usuario
            # Se guarda el registro de usuario
            userFormRequest.save()
            userFormSave = userFormRequest.save()

            # Se crea el registro del estudiante pero no se guarda
            studentFormSave = studentFormRequest.save(commit=False)
            # Asignamos el usuario al estudiante
            studentFormSave.user = userFormSave
            # Guardamos el estudiante
            studentFormSave.save()
            return render(request, "myAccount/successfulStudentUpdate.html")
        else:
            logging.error("Es invalido")
            return render(request, "myAccount/studentModify.html", {
                "studentForm": studentFormRequest,
                "userForm": userFormRequest
            })
    return render(request, "myAccount/studentModify.html", {
        "studentForm": StudentForm(prefix='student', instance=student),
        "userForm": userFormChange(prefix='user', instance=user)
    })


@login_required(login_url="login")
def studentDelete(request):
    return


@login_required(login_url="login")
def myAccount(request):
    if request.user.is_staff:
        return redirect('admin:index')
    return render(request, "myAccount/myAccount.html", {

    })


@login_required(login_url="login")
def followedLessons(request):
    if request.user.is_staff:
        return redirect('admin:index')
    estudiante = Estudiante.objects.get(user=request.user)
    estudianteLecciones = Estudiante_Leccione.objects.filter(
        estudiante=estudiante)
    return render(request, "myAccount/lessonsList.html", {
        "lessons": estudianteLecciones
    })


@login_required(login_url="login")
def loginRedirect(request):
    if request.user.is_staff:
        return redirect('admin:index')
    else:
        return redirect('LearningCatalog:listLesson')

myAccount/templates/myAccount/exampleTemplate.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<head>
    <title>Registro de estudiantes</title>
</head>

<div class="container">
    <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-5">
        <div class="row">
            <div class="col-12">
                <h1 class="display-4 mb-3">
                    Ejemplo
                    <span class="material-icons-outlined align-middle blueIcons" style="font-size: 48px;">
                        account_circle
                    </span>
                </h1>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col">

            </div>
        </div>
    </div>
</div>
{% endblock %}

myAccount/templates/myAccount/lessonsList.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<head>
    <title>Mis Lecciones</title>
</head>

<div class="container">
    <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-5">
        <div class="row">
            <div class="col-12">
                <h1 class="display-4 mb-3">
                    Mis Lecciones seguidas
                    <span class="material-icons-outlined align-middle blueIcons" style="font-size: 48px;">
                        menu_book
                    </span>
                </h1>
            </div>
        </div>
        <hr>
        <div class="row">
            {% for lesson in lessons %}
            <div class="col-12 col-md-6 col-lg-4 mt-3">
                <div class="card mx-auto mx-md-0" style="width: 18rem;">
                    <img src="{{lesson.leccion.imagen.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{lesson.leccion.titulo}}</h5>
                        <p class="card-text">{{lesson.leccion.descripcion}}</p>
                        <a href="{% url 'LearningCatalog:readLesson' lesson.leccion.pk %}" class="btn btn-primary">
                            Ver contenido
                            <span class="material-icons-outlined align-middle">
                                arrow_forward
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col">
                <p>No hay lecciones</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

myAccount/templates/myAccount/myAccount.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<head>
    <title>Mi cuenta</title>
</head>

<div class="container">
    <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-5">
        <div class="row">
            <div class="col-12">
                <h1 class="display-4 mb-3">
                    Mi cuenta
                    <span class="material-icons-outlined align-middle blueIcons" style="font-size: 48px;">
                        account_circle
                    </span>
                </h1>
            </div>
        </div>
        <hr>
        <div class="row mb-5">
            <div class="col-md-4 text-center">
                <a href="{% url 'myAccount:studentRead' %}" class="btn customBtn rounded shadow-lg h-100">
                    <h4>
                        Mis datos personales
                    </h4>
                    <span class="material-icons-outlined blueIcons" style="font-size: 48px;">
                        contact_mail
                    </span>
                    <small class="form-text text-muted font-weight-bold">
                        Mi información personal de la cuenta Educap
                    </small>
                </a>
            </div>
            <div class="col-md-4 mt-5 mt-md-0 text-center">
                <a href="{% url 'myAccount:followedLessons' %}" class="btn customBtn rounded shadow-lg h-100">
                    <h4>
                        Mis leccciones
                    </h4>
                    <span class="material-icons-outlined blueIcons" style="font-size: 48px;">
                        menu_book
                    </span>
                    <small class="form-text text-muted font-weight-bold">
                        Listado todas las lecciones que sigues
                    </small>
                </a>

            </div>

        </div>
    </div>
</div>
{% endblock %}

myAccount/templates/myAccount/studentCreate.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<head>
  <title>Registro de estudiantes</title>
</head>

<div class="container">
  <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-5">
    <div class="row">
      <div class="col-12">
        <h1 class="display-4 mb-3">
          Registro de estudiantes
          <span class="material-icons-outlined align-bottom redIcons " style="font-size: 48px;">
            person_add
          </span>
        </h1>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-12">
        <form action="{% url 'myAccount:studentCreate' %}" method="POST">
          {% csrf_token %}
      
            <div class="form-row">
              <div class="form-group col-md-6">
                {{userForm.email|as_crispy_field}}
              </div>
              <div class="form-group col-md-2">
                {{studentForm.edad|as_crispy_field}}
              </div>
            </div>

            <div class="form-row">
              <div class="form-group col-md-6">
                {{userForm.first_name|as_crispy_field}}
              </div>
              <div class="form-group col-md-6">
                {{userForm.last_name|as_crispy_field}}
              </div>
            </div>

            <div class="form-row">
              <div class="form-group col-md-6">
                {{userForm.password1|as_crispy_field}}
              </div>
              <div class="form-group col-md-6">
                {{userForm.password2|as_crispy_field}}
              </div>
            </div>
            {{userForm.errors}}
            {{studentForm.errors}}
            
          <button type="submit" class="btn btn-primary float-right mr-3">Registrar</button>
        </form>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'cuentas/slides.js' %}"></script>
{% endblock %}

myAccount/templates/myAccount/studentModify.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<head>
    <title>Modificar cuenta</title>
</head>

<div class="container">
    <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-5">
        <div class="row">
            <div class="col-12">
                <h1 class="display-4 mb-3">
                    Modificar información personal
                    <span class="material-icons-outlined align-middle redIcons " style="font-size: 48px;">
                        edit
                    </span>
                </h1>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-12">
                <form action="{% url 'myAccount:studentUpdate' %}" method="POST">
                    {% csrf_token %}

                    <div class="form-row">
                        <div class="form-group col-md-2">
                            {{studentForm.edad|as_crispy_field}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            {{userForm.first_name|as_crispy_field}}
                        </div>
                        <div class="form-group col-md-6">
                            {{userForm.last_name|as_crispy_field}}
                        </div>
                    </div>
                    {{userForm.errors}}
                    {{studentForm.errors}}
                    <button type="submit" class="btn btn-primary float-right mr-3">Registrar</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

myAccount/templates/myAccount/studentRead.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<head>
    <title>Mi información personal</title>
</head>

<div class="container">
    <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-5">
        <div class="row">
            <div class="col-12">
                <h1 class="display-4 mb-3">
                    Mi información personal
                    <span class="material-icons-outlined align-middle blueIcons" style="font-size: 48px;">
                        account_circle
                    </span>
                </h1>
            </div>
        </div>
        <hr>
        <div class="row my-auto justify-content-between">
            <div class="col-12 col-lg-6">
                <h4 class="align-middle">Nombre:</h4>
                <label class="text-muted user-select-none">{{ user.first_name }} {{ user.last_name }}</label>
            </div>
            <div class="col-12 col-lg-4 my-auto">
                <a href="{% url 'myAccount:studentUpdate' %}" class="btn btn-secondary float-right">
                    Modificar información
                </a>
            </div>
        </div>
        <hr>
        <div class="row justify-content-between">
            <div class="col-lg-6">
                <h4>Edad:</h4>
                <label class="text-muted user-select-none">{{ student.edad }}</label>
            </div>
            <div class="col-lg-4 my-auto">
            </div>
        </div>
        <hr>
        <div class="row justify-content-between">
            <div class="col-lg-6">
                <h4>Correo electronico:</h4>
                <label class="text-muted user-select-none">{{ user }}</label>
            </div>
        </div>
        <hr>
        <div class="row justify-content-between">
            <div class="col-lg-6">
                <h4>Contraseña:</h4>
                <label class="text-muted user-select-none">**************</label>
            </div>
            <div class="col-lg-4 my-auto">
                <a href="{% url 'password_change' %}" class="btn btn-primary float-right">Cambiar
                    contraseña</a>
            </div>
        </div>
        <hr>
    </div>
</div>
{% endblock %}

myAccount/templates/myAccount/successfulStudentCreate.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% block body %}
<div class="container" id="multifuncioanes">
    <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-1">
        <div class="row">
            <div class="col-12">
                <h2 class="display-4 text-break">
                    Cuenta creada exitosamente!
                    <span class="material-icons-outlined redIcons align-bottom mr-1 " style="font-size: 48px;">
                        task_alt
                    </span>
                </h2>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-12">
                <a class="btn btn-primary" href="{% url 'login' %}">Iniciar sesión</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

myAccount/templates/myAccount/successfulStudentUpdate.html
{% extends 'LearningCatalog/layout.html' %}
{% load static %}
{% block body %}
<div class="container" id="multifuncioanes">
    <div class="jumbotron mt-5 bg-light mr-0 ml-0 shadow mb-1">
        <div class="row">
            <div class="col-12">
                <h2 class="display-4 text-break">
                    Cuenta actualizada exitosamente!
                    <span class="material-icons-outlined redIcons align-bottom mr-1 " style="font-size: 48px;">
                        task_alt
                    </span>
                </h2>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-12">
                <a class="btn btn-primary" href="{% url 'myAccount:myAccount' %}">Volver a mi cuenta</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}